name: makc_app
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8

 #==================== FIREBASE ====================#
  # firebase_core: ^3.1.1
  # firebase_core_platform_interface: ^6.0.0
  # firebase_messaging: ^15.0.0
  # flutter_local_notifications: ^18.0.1
  # firebase_performance: ^0.10.1+10
  

  #==================== STATE MANAGEMENT ====================#
  get: ^4.6.6



  #==================== NETWORK ====================#
  http:
  dio: ^5.3.3

  #==================== UI & UX ====================#
  flutter_screenutil: ^5.9.3
  pull_to_refresh: ^2.0.0
  flutter_staggered_grid_view: ^0.7.0
  lottie: ^3.3.0
  upgrader: ^10.3.0
  flutter_html: ^3.0.0-beta.2
  flutter_svg: ^2.0.12
  video_player: ^2.10.0
  carousel_slider: ^5.1.0 
  table_calendar: ^3.0.9

  
  
 

  #==================== MAPS & LOCATION ====================#
  permission_handler: ^11.0.1
  

  #==================== LOCAL STORAGE ====================#
  get_storage: ^2.1.1

  #==================== UTILITIES ====================#
  
  intl: ^0.20.2
  url_launcher: ^6.2.1
  sms_autofill: ^2.4.1

  #==================== MEDIA ====================#
  photo_view: ^0.15.0
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0



flutter:


  uses-material-design: true


  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/icons/
    - assets/animations/


  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
